---

- name: Configuring Windows 10
  hosts: all
  vars:
  tasks:
    - name: Install neovim
      win_chocolatey:
        name: neovim
        state: latest
        allow_prerelease: yes

    - name: Install software
      win_chocolatey:
        name:
        - git
        - delta
        - sed
        - 7zip
        - vscode
        - powershell-preview
        state: present

    - name: Set cmd prompt and aliases
      win_regedit:
        path: 'HKLM:\Software\Microsoft\Command Processor'
        name: AutoRun
        data: 'prompt $E[92m%USERNAME%@%COMPUTERNAME%$E[0m:$E[32m$P$E[0m$_$E(0mq$E(B cmd$G & doskey ls=dir $* & doskey cat=type $* & doskey reboot=shutdown /r /t 0 $*'
        type: string

    - name: Install Fantastique Sans Mono
      debug:
        msg: "Don't forget!"

    - name: Copy neovim configuration
      win_copy:
        src: files/init.vim
        dest: '%LocalAppData%\nvim\init.vim'

    - name: Enable WSL
      win_optional_feature:
        name: Microsoft-Windows-Subsystem-Linux
        state: present

    - name: Set COLORTERM environment variable (for delta)
      win_environment:
        name: COLORTERM
        value: truecolor
        level: user
        state: present

    - name: Find latest Nerd Fonts release
      win_uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        return_content: true
      register: nerdfonts_release

    - set_fact:
        dl_url: "{{ nerdfonts_release.json.assets | selectattr('name', 'equalto', 'FantasqueSansMono.zip') | list }}"

    - name: Download font
      win_get_url:
        url: "{{ dl_url[0].browser_download_url }}"
        dest: "%USERPROFILE%/FantasqueSansMono.zip"

    - name: Download and extract Fantasque Sans Mono Nerd Font
      win_unzip:
        src: "%USERPROFILE%/FantasqueSansMono.zip"
        dest: "%USERPROFILE%/FantasqueSansMonoUnzip"

