---

- name: Configuring Windows 10
  hosts: all
  vars:
    ansible_shell_type: cmd
  tasks:
    - name: Install neovim
      win_chocolatey:
        name: neovim
        state: latest
        allow_prerelease: yes

    - name: Install software
      win_chocolatey:
        name:
        - git
        - delta
        - sed
        - 7zip
        - vscode
        - powershell-preview
        state: present

    - name: Set cmd prompt and aliases
      win_regedit:
        path: 'HKLM:\Software\Microsoft\Command Processor'
        name: AutoRun
        data: 'prompt $E[32m%USERNAME%@%COMPUTERNAME%$E[0m:$E[34m$P$E[0m$_$E(0mq$E(B cmd$G & doskey ls=dir $* & doskey cat=type $* & doskey reboot=shutdown /r /t 0 $* & doskey clear=cls'
        type: string

    - name: Install Fantastique Sans Mono
      debug:
        msg: "Don't forget!"

    - name: Copy neovim configuration
      win_copy:
        src: files/init.vim
        dest: '%LocalAppData%\nvim\init.vim'

    - name: Enable WSL
      win_optional_feature:
        name: Microsoft-Windows-Subsystem-Linux
        state: present

    - name: Set COLORTERM environment variable (for delta)
      win_environment:
        name: COLORTERM
        value: truecolor
        level: user
        state: present

    - name: Find latest Nerd Fonts release
      win_uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        return_content: true
      register: nerdfonts_release

    - name: Get download url
      set_fact:
        dl_url: "{{ nerdfonts_release.json.assets | selectattr('name', 'equalto', 'FantasqueSansMono.zip') | list }}"

    - name: Download font
      win_get_url:
        url: "{{ dl_url[0].browser_download_url }}"
        dest: '{{ ansible_env["TEMP"] }}\FantasqueSansMono.zip'

    - name: Extract Fantasque Sans Mono Nerd Font
      win_unzip:
        src: '{{ ansible_env["TEMP"] }}\FantasqueSansMono.zip'
        dest: '{{ ansible_env["TEMP"] }}\FantasqueSansMonoUnzip'

    - name: Find font files
      win_find:
        paths: '{{ ansible_env["TEMP"] }}\FantasqueSansMonoUnzip'
        patterns: [ '*.ttf' ]
      register: fontfiles

    - name: Install font
      win_shell: |
        $SystemFontsFolder = (New-Object -ComObject Shell.Application).Namespace(0x14)
        $targetPath = Join-Path "${env:LocalAppData}\Microsoft\Windows\Fonts" '{{ item.filename }}'
        # So, see if target exists...
        if (-not (Test-Path $targetPath)) {
          #install the font.
          $SystemFontsFolder.CopyHere('{{ item.path }}')
          Write-Output "change made"
        }
      register: _fontinstall_command
      changed_when: "'change made' in _fontinstall_command.stdout"
      loop: "{{ fontfiles.files }}"
      loop_control:
        label: "{{ item.filename }}"

