---

- name: Configuring Windows 10
  hosts: all
  vars:
  tasks:
    - name: Install neovim
      win_chocolatey:
        name: neovim
        state: latest
        allow_prerelease: yes

    - name: Install software
      win_chocolatey:
        name:
        - git
        - sed
        - 7zip.install
        - vscode
        - powershell-preview
        state: present

    - name: Set cmd prompt and aliases
      win_regedit:
        path: 'HKLM:\Software\Microsoft\Command Processor'
        name: AutoRun
        data: 'prompt $E[92m%USERNAME%@%COMPUTERNAME%$E[0m:$E[32m$P$E[0m$_$E(0mq$E(B cmd$G & doskey ls=dir $* & doskey cat=type $* & doskey reboot=shutdown /r /t 0 $*'
        type: string

    - name: Install Fantastique Sans Mono
      debug:
        msg: "Don't forget!"

    - name: Configure init.vim
      win_copy:
        dest: '%LocalAppData%\nvim\init.vim'
        content: |
          " Neovim configuration file

          set number
          set background=dark

          " Turn off backup and swapfiles
          set nobackup
          set nowritebackup
          set noswapfile

          " 4 spaces instead of Tab
          set expandtab
          set shiftwidth=4
          set tabstop=4

          " Ignore case when searching
          set ignorecase

          " Copy to system clipboard with Ctrl-C
          vnoremap <C-c> "+y

          " Set to auto read when a file is changed from the outside
          set autoread

          " Keep 4 lines on screen ahead of the cursor 
          set scrolloff=4

          " Show matching bracket when cursor is hovering one
          set showmatch

          " Set indentation to 2 spaces for YAML
          autocmd FileType yaml setlocal shiftwidth=2 tabstop=2 

          " Highlight current line
          set cursorline
          highlight CursorLine cterm=none
          highlight CursorLineNR cterm=inverse
          
          " No fat background highlight on split divider
          highlight VertSplit cterm=NONE

          " Render invisible characters
          set list
          "set listchars=tab:→\ ,space:·,nbsp:␣,trail:·,eol:↲
          set listchars=tab:→\ ,nbsp:␣,trail:·,eol:↲
          highlight NonText ctermfg=0

          " Load vim-plug plugins
          call plug#begin()
          Plug 'sheerun/vim-polyglot'
          Plug 'ryanoasis/vim-devicons'
          Plug 'preservim/nerdtree'
          Plug 'Yggdroot/indentLine'
          Plug 'itchyny/lightline.vim'
          Plug 'neoclide/coc.nvim', {'branch': 'release'}
          call plug#end()

          " Lightline configurations
          set noshowmode
          let g:lightline = {
              \ 'colorscheme': 'wombat',
              \ }

          " Configure Indent-Guide
          let g:indentLine_char = '▏'

          " Open NERDTree with Ctrl + B
          map <C-b> :NERDTreeToggle<CR>

          " Show hidden dotfiles by default in NERDTree
          let NERDTreeShowHidden=1

          " Close vim if the only window left open is NERDTree
          autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

    - name: Enable WSL
      win_optional_feature:
        name: Microsoft-Windows-Subsystem-Linux
        state: present

    - name: Find latest Nerd Fonts release
      win_uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        return_content: true
      register: nerdfonts_release

    - set_fact:
        dl_url: "{{ nerdfonts_release.json.assets | selectattr('name', 'equalto', 'FantasqueSansMono.zip') | list }}"

    - name: Download font
      win_get_url:
        url: "{{ dl_url[0].browser_download_url }}"
        dest: "%USERPROFILE%/FantasqueSansMono.zip"

    - name: Download and extract Fantasque Sans Mono Nerd Font
      win_unzip:
        src: "%USERPROFILE%/FantasqueSansMono.zip"
        dest: "%USERPROFILE%/FantasqueSansMonoUnzip"

