---

- name: Configuring Windows 10
  hosts: all
  vars:
    ansible_shell_type: cmd
    nerdfonts_to_install:
      - FantasqueSansMono.zip
      - FiraCode.zip
      - JetBrainsMono.zip
  tasks:
    - name: Install neovim
      win_chocolatey:
        name: neovim
        state: latest
        allow_prerelease: yes

    - name: Install software
      win_chocolatey:
        name: git
        package_params: '/GitOnlyOnPath /WindowsTerminal /NoShellIntegration /NoCredentialManager /SChannel'

    - name: Install software
      win_chocolatey:
        name:
        - delta
        - sed
        - 7zip
        - vscode
        - powershell-preview
        state: present

    - name: Set cmd prompt and aliases
      win_regedit:
        path: 'HKLM:\Software\Microsoft\Command Processor'
        name: AutoRun
        data: 'prompt $E[32m%USERNAME%@%COMPUTERNAME%$E[0m:$E[34m$P$E[0m$_$E(0mq$E(B cmd$G & doskey ls=dir $* & doskey cat=type $* & doskey reboot=shutdown /r /t 0 $* & doskey clear=cls'
        type: string

    - name: Copy neovim configuration
      win_copy:
        src: files/init.vim
        dest: '%LocalAppData%\nvim\init.vim'

    - name: Enable WSL
      win_optional_feature:
        name: Microsoft-Windows-Subsystem-Linux
        state: present

    - name: Set COLORTERM environment variable (for delta)
      win_environment:
        name: COLORTERM
        value: truecolor
        level: user
        state: present

    - name: Find latest Nerd Fonts release
      win_uri:
        url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
        return_content: true
      register: nerdfonts_release

    - name: Get font download URLs
      set_fact:
        font_dl_urls: "{{ font_dl_urls | default([]) + nerdfonts_release.json.assets | selectattr('name', 'equalto', item) }}"
      loop: '{{ nerdfonts_to_install }}'

    - name: Download fonts
      win_get_url:
        url: "{{ item.browser_download_url }}"
        dest: '{{ ansible_env["TEMP"] }}\{{ item.name }}'
      loop: '{{ font_dl_urls }}'
      throttle: 1

    - name: Extract Fantasque Sans Mono Nerd Font
      win_unzip:
        src: '{{ ansible_env["TEMP"] }}\{{ item.name }}'
        dest: '{{ ansible_env["TEMP"] }}\{{ item.name }}-unzip'
        creates: '{{ ansible_env["TEMP"] }}\{{ item.name }}-unzip'
      loop: '{{ font_dl_urls }}'

    - name: Find font files
      win_find:
        paths: '{{ ansible_env["TEMP"] }}\{{ item.name }}-unzip'
        patterns: [ '*.ttf' ]
      loop: '{{ font_dl_urls }}'
      register: fontfiles

    - name: Install font
      win_shell: |
        $SystemFontsFolder = (New-Object -ComObject Shell.Application).Namespace(0x14)
        $targetPath = Join-Path "${env:LocalAppData}\Microsoft\Windows\Fonts" -ChildPath '{{ item.filename }}'
        # So, see if target exists...
        if (-not (Test-Path $targetPath)) {
          #install the font.
          $SystemFontsFolder.CopyHere('{{ item.path }}')
          Write-Output "change made"
        }
      register: _fontinstall_command
      changed_when: "'change made' in _fontinstall_command.stdout"
      loop: "{{ fontfiles.results | map(attribute='files') | flatten }}"
      loop_control:
        label: "{{ item.filename }}"

