#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         4
bspc config window_gap          12
bspc config click_to_focus      true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

feh --bg-center /home/jantari/Bilder/mN26CKe.jpg
wal -i /home/jantari/Bilder/mN26CKe.jpg
polybar top &

# Source wal-colors for use in bspwm
. "${HOME}/.cache/wal/colors.sh"

# Set bspwm colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

